### ISSUE TITLE
Cant choose image to upload ID card

### ISSUE THREAD

**Issue by LocNguyennn** [roshan9419/CafyTheOfficeCafeteria#1]
![bug](https://user-images.githubusercontent.com/91452158/154688243-8eeb3307-bf3c-49e9-84aa-90992229deea.png)
hey, it's me, I'm already asking you on your Youtube channel. Here is my issue, this happened when I click "choose image" to upload an ID card, how can I fix it?

**Comment by roshan9419** [comment]
Hey,
It's not the code issue, the main issue is your emulator. It is trying to find any camera but not able to do so, that' why they are saying they couldn't find it. You might not enable the camera in the emulator. Please check the settings by clicking on the 3 dots below in the emulator controller. You can try it on a real device also to verify.

Please let me know if that fixes...

**Comment by LocNguyennn** [comment]
wow, tks you so much for your help, I solved it. Your project is so cool !!
